test: fix test for Strings#stripTags
1) Strings
     #stripTags(str)
       should throw an error if any argument is null:

    AssertionError: expected [Function] to throw 'ReferenceError' but 'TypeError: Cannot read property \'replace\' of undefined' was thrown
    + expected - actual

    -TypeError: Cannot read property 'replace' of undefined
    +ReferenceError

    at Context.<anonymous> (test/StringsTest.js:142:49)
    at processImmediate (internal/timers.js:461:21)